name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC",
              os: windows-latest,
              generator: "",
              build_type: release,
              cc: "cl", cxx: "cl",
              dependencies: "",
              build_product: "kokko-editor.exe"
            }
          - {
              name: "Linux GCC",
              os: ubuntu-latest,
              generator: "",
              build_type: release,
              cc: "gcc", cxx: "g++",
              dependencies: "sudo apt-get update && sudo apt-get install xorg-dev",
              build_product: "kokko-editor"
            }
          - {
              name: "MacOS Clang",
              os: macos-latest,
              generator: "-G Xcode",
              build_type: release,
              cc: "clang", cxx: "clang",
              dependencies: "",
              build_product: "kokko-editor"
            }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: ${{matrix.config.dependencies}}

    - name: Configure
      env:
        CC: ${{matrix.config.cc}}
        CXX: ${{matrix.config.cxx}}
      run: |
        mkdir build
        cmake -B build ${{matrix.config.generator}} -DWEBP_BUILD_ANIM_UTILS=OFF -DWEBP_BUILD_CWEBP=OFF -DWEBP_BUILD_DWEBP=OFF -DWEBP_BUILD_LIBWEBPMUX=OFF -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}

    - name: Build
      # GitHub runners have 2 vCPU, run 3 parallel build jobs
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}} --parallel 3

    - name: Run tests
      run: ${{github.workspace}}/build/bin/${{matrix.config.build_type}}/${{matrix.config.build_product}} --exit=true
