name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows MSVC",
              os: windows-latest,
              generator: "",
              cmake_defines: "",
              build_type: Release,
              cc: "cl", cxx: "cl",
              compile_flags: "",
              link_flags: "",
              dependencies: "",
              build_product: "kokko-editor.exe"
            }
          - {
              name: "Linux GCC",
              os: ubuntu-latest,
              generator: "",
              cmake_defines: "",
              build_type: Release,
              cc: "gcc", cxx: "g++",
              dependencies: "sudo apt-get update && sudo apt-get install xorg-dev",
              build_product: "kokko-editor"
            }
          - {
              name: "Linux GCC ASan",
              os: ubuntu-latest,
              generator: "",
              cmake_defines: "-DKOKKO_USE_SANITIZER=address",
              build_type: Release,
              cc: "gcc", cxx: "g++",
              dependencies: "sudo apt-get update && sudo apt-get install xorg-dev",
              build_product: "kokko-editor"
            }
          - {
              name: "Linux GCC TSan",
              os: ubuntu-latest,
              generator: "",
              cmake_defines: "-DKOKKO_USE_SANITIZER=thread",
              build_type: Release,
              cc: "gcc", cxx: "g++",
              dependencies: "sudo apt-get update && sudo apt-get install xorg-dev",
              build_product: "kokko-editor"
            }
          - {
              name: "Linux GCC UBSan",
              os: ubuntu-latest,
              generator: "",
              cmake_defines: "-DKOKKO_USE_SANITIZER=undefined",
              build_type: Release,
              cc: "gcc", cxx: "g++",
              dependencies: "sudo apt-get update && sudo apt-get install xorg-dev",
              build_product: "kokko-editor"
            }
          - {
              name: "MacOS Clang",
              os: macos-latest,
              generator: "-G Xcode",
              cmake_defines: "",
              build_type: Release,
              cc: "clang", cxx: "clang",
              dependencies: "",
              build_product: "kokko-editor"
            }

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: ${{matrix.config.dependencies}}

    - name: Configure
      env:
        CC: ${{matrix.config.cc}}
        CXX: ${{matrix.config.cxx}}
      run: |
        mkdir build
        cmake -B build ${{matrix.config.generator}} ${{matrix.config.cmake_defines}} -DWEBP_BUILD_ANIM_UTILS=OFF -DWEBP_BUILD_CWEBP=OFF -DWEBP_BUILD_DWEBP=OFF -DWEBP_BUILD_LIBWEBPMUX=OFF -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}} --parallel

    - name: Run tests
      run: |
        ${{github.workspace}}/build/bin/${{matrix.config.build_type}}/${{matrix.config.build_product}} --exit=true
