name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
              name: "Windows Latest MSVC",
              os: windows-latest,
              build_type: Release,
              cc: "cl", cxx: "cl",
              dependencies: ""
            }
          - {
              name: "Ubuntu Latest GCC",
              os: ubuntu-latest,
              build_type: Release,
              cc: "gcc", cxx: "g++",
              dependencies: "sudo apt-get install xorg-dev"
            }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install dependencies
      run: ${{matrix.config.dependencies}}

    - name: Configure CMake
      env:
        CC: ${{matrix.config.cc}}
        CXX: ${{matrix.config.cxx}}
      run: |
        mkdir ${{github.workspace}}/samples/build
        cmake -B ${{github.workspace}}/samples/build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/samples/build --config ${{matrix.config.build_type}}
